m2l_annonces_home:
    path: /annonces
    defaults: { _controller: M2LAnnoncesBundle:Annonces:index }

m2l_annonces_view:
    path: /annonces/{id}
    defaults: { _controller: M2LAnnoncesBundle:Annonces:view }

m2l_annonces_add:
    path: /anonnces/add
    defaults: { _controller: M2LAnnoncesBundle:Annonces:add }

m2l_annonces_post:
    path: /annonces/mes-annonces
    defaults: { _controller: M2LAnnoncesBundle:Annonces:add }
