m2l_inscription:
    path:   /inscription
    defaults: { _controller: M2LUserBundle:User:inscription }

login:
    pattern:   /login
    defaults:  { _controller: M2LUserBundle:User:login }

login_check:
    pattern:   /login_check