m2l_inscription:
    path:   /inscription
    defaults: { _controller: M2LUserBundle:User:inscription }

login:
    pattern:   /login
    defaults:  { _controller: M2LUserBundle:User:login }

login_check:
    pattern:   /login_check

m2l_profil_edit:
    path:    /profil/edit
    defaults: { _controller: M2LUserBundle:User:edit }