M2L\UserBundle\Entity\User:
    properties:
        pseudo:
            - NotBlank: ~

        nom:
            - NotBlank: ~

        password:
            - NotBlank: ~
    
        ddn:
            - NotBlank: ~

        ville:
            - NotBlank: ~

        sexe:
            - NotBlank: ~

        email:
            - Email: ~